#!/bin/bash

# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!

#SBATCH -p gpu_short
#SBATCH --gpus-per-node 1
#SBATCH --job-name=worker
#SBATCH --output=logs/worker.log
#SBATCH --error=logs/worker.errors.log

source /users/lindgren/hjo721/job-scripts/conda.sh aminosgym

ray start --address="${HEAD_IP}:${HEAD_PORT}" --block